PanelAdministracyjny/src/java/database/entities/MapPoint.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package database.entities;

import contentView.ApplicationUtil;
import java.io.Serializable;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;

/**
 *
 * @author Tomek
 */
@Entity
@Table(name = "MapPoint")
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "MapPoint.findAll", query = "SELECT m FROM MapPoint m"),
    @NamedQuery(name = "MapPoint.findById", query = "SELECT m FROM MapPoint m WHERE m.id = :id"),
    @NamedQuery(name = "MapPoint.findByLatitude", query = "SELECT m FROM MapPoint m WHERE m.latitude = :latitude"),
    @NamedQuery(name = "MapPoint.findByLongitude", query = "SELECT m FROM MapPoint m WHERE m.longitude = :longitude"),
    @NamedQuery(name = "MapPoint.findByRadius", query = "SELECT m FROM MapPoint m WHERE m.radius = :radius"),
    @NamedQuery(name = "MapPoint.findByLabel", query = "SELECT m FROM MapPoint m WHERE m.label = :label"),
    @NamedQuery(name = "MapPoint.findByShortInfo", query = "SELECT m FROM MapPoint m WHERE m.shortInfo = :shortInfo"),
    @NamedQuery(name = "MapPoint.findByLastUpdate", query = "SELECT m FROM MapPoint m WHERE m.lastUpdate = :lastUpdate"),
    @NamedQuery(name = "MapPoint.findByRegion", query = "SELECT m FROM MapPoint m WHERE m.region = :region"),
    @NamedQuery(name = "MapPoint.findByAddress", query = "SELECT m FROM MapPoint m WHERE m.address = :address")})
public class MapPoint implements Serializable {
    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name = "ID")
    private Integer id;
    @Basic(optional = false)
    @NotNull
    @Column(name = "Latitude")
    private double latitude;
    @Basic(optional = false)
    @NotNull
    @Column(name = "Longitude")
    private double longitude;
    @Column(name = "Radius")
    private Integer radius;
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 100)
    @Column(name = "Label")
    private String label;
    @Size(max = 500)
    @Column(name = "ShortInfo")
    private String shortInfo;
    @Lob
    @Size(max = 16777215)
    @Column(name = "FullInfo")
    private String fullInfo;
    @Basic(optional = false)
    @Column(name = "LastUpdate")
    @Temporal(TemporalType.TIMESTAMP)
    private Date lastUpdate;
    @Size(max = 50)
    @Column(name = "Region")
    private String region;
    @Size(max = 100)
    @Column(name = "Address")
    private String address;

    public MapPoint() {
    }

    public MapPoint(Integer id) {
        this.id = id;
    }

    public MapPoint(Integer id, double latitude, double longitude, String label, Date lastUpdate) {
        this.id = id;
        this.latitude = latitude;
        this.longitude = longitude;
        this.label = label;
        this.lastUpdate = lastUpdate;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public double getLatitude() {
        return latitude;
    }

    public void setLatitude(double latitude) {
        this.latitude = latitude;
    }

    public double getLongitude() {
        return longitude;
    }

    public void setLongitude(double longitude) {
        this.longitude = longitude;
    }

    public Integer getRadius() {
        return radius;
    }

    public void setRadius(Integer radius) {
        this.radius = radius;
    }

    public String getLabel() {
        return label;
    }

    public void setLabel(String label) {
        this.label = label;
    }

    public String getShortInfo() {
        return shortInfo;
    }

    public void setShortInfo(String shortInfo) {
        this.shortInfo = shortInfo;
    }

    public String getFullInfo() {
        return fullInfo;
    }

    public void setFullInfo(String fullInfo) {
        this.fullInfo = fullInfo;
    }

    public Date getLastUpdate() {
        return lastUpdate;
    }

    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    public String getRegion() {
        return region;
    }

    public void setRegion(String region) {
        this.region = region;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (id != null ? id.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof MapPoint)) {
            return false;
        }
        MapPoint other = (MapPoint) object;
        if ((this.id == null && other.id != null) || (this.id != null && !this.id.equals(other.id))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "database.entities.MapPoint[ id=" + id + " ]";
    }
    
}

PanelAdministracyjny/src/java/contentView/controllers/MapPointController.java
package contentView.controllers;

import contentView.ApplicationUtil;
import contentView.JsfUtil;
import contentView.PaginationHelper;
import database.entities.MapPoint;
import database.manager.MapPointFacade;

import java.io.Serializable;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;

@ManagedBean(name = "mapPointController")
@SessionScoped
public class MapPointController implements Serializable {
    
    private MapPoint current;
    private DataModel items = null;
    @EJB
    private database.manager.MapPointFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;

    public MapPointController() {
    }

    public MapPoint getSelected() {
        if (current == null) {
            current = new MapPoint();
            selectedItemIndex = -1;
        }
        return current;
    }

    private MapPointFacade getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {
                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (MapPoint) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new MapPoint();
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        try {
            ApplicationUtil util = new ApplicationUtil();
            current.setAddress(util.reverseGeocode(Double.toString(current.getLatitude()), Double.toString(current.getLongitude())));            
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/i18n.text").getString("MapPointCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/i18n.text").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        try {
            current = (MapPoint) getItems().getRowData();
        }
        catch(Exception e) {}
        
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/i18n.text").getString("MapPointUpdated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/i18n.text").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (MapPoint) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/i18n.text").getString("MapPointDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/i18n.text").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    @FacesConverter(forClass = MapPoint.class)
    public static class MapPointControllerConverter implements Converter {

        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            MapPointController controller = (MapPointController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "mapPointController");
            return controller.ejbFacade.find(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuffer sb = new StringBuffer();
            sb.append(value);
            return sb.toString();
        }

        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof MapPoint) {
                MapPoint o = (MapPoint) object;
                return getStringKey(o.getId());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + MapPoint.class.getName());
            }
        }
    }
}

PanelAdministracyjny/web/mapPoint/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">
    <ui:composition template="/WEB-INF/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{text.CreateMapPointTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <div id="table">
                <div id="table2">
                    <h:form prependId="false">
                        <h:panelGrid columns="2" styleClass="panelGrid">
                            <h:outputLabel value="#{text.Latitude}" for="latitude" />
                            <h:inputText id="latitude" value="#{mapPointController.selected.latitude}" required="true" requiredMessage="#{text.Required}"/>
                            <h:outputLabel value="#{text.Longitude}" for="longitude" />
                            <h:inputText id="longitude" value="#{mapPointController.selected.longitude}" required="true" requiredMessage="#{text.Required}"/>
                            <h:outputLabel value="#{text.Radius}" for="radius" />
                            <h:inputText id="radius" value="#{mapPointController.selected.radius}"  />
                            <h:outputLabel value="#{text.Label}" for="label" />
                            <h:inputText id="label" value="#{mapPointController.selected.label}" required="true" requiredMessage="#{text.Required}"/>
                            <h:outputLabel value="#{text.ShortInfo}" for="shortInfo" />
                            <h:inputText id="shortInfo" value="#{mapPointController.selected.shortInfo}" />
                            <h:outputLabel value="#{text.FullInfo}" for="fullInfo" />
                            <h:inputTextarea rows="4" cols="30" id="fullInfo" value="#{mapPointController.selected.fullInfo}" />
                            <h:outputLabel value="#{text.Region}" for="region" />
                            <h:selectOneMenu id="region" value="#{mapPointController.selected.region}">
                                <f:selectItem itemValue="Pomorze" itemLabel="Pomorze" />
                                <f:selectItem itemValue="Polska centralna" itemLabel="Polska centralna" />
                                <f:selectItem itemValue="Śląsk" itemLabel="Śląsk" />
                            </h:selectOneMenu>
                        </h:panelGrid>
                        <div class="marginLeft">
                            <h:commandLink action="#{mapPointController.create}" value="#{text.Save}" />
                            <br />
                            <h:commandLink action="#{mapPointController.prepareList}" value="#{text.Back}" immediate="true"/>
                        </div>
                    </h:form>
                </div>
            </div>
        </ui:define>
    </ui:composition>
</html>

PanelAdministracyjny/web/mapPoint/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">
    <ui:composition template="/WEB-INF/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{text.EditMapPointTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">            
            <div id="table">
                <div id="table2">
                    <h:form prependId="false">
                        <h:panelGrid columns="2">
                            <h:outputLabel value="#{text.Latitude}" for="latitude" />
                            <h:inputText id="latitude" value="#{mapPointController.selected.latitude}" required="true" requiredMessage="#{text.Required}"/>
                            <h:outputLabel value="#{text.Longitude}" for="longitude" />
                            <h:inputText id="longitude" value="#{mapPointController.selected.longitude}" required="true" requiredMessage="#{text.Required}"/>
                            <h:outputLabel value="#{text.Radius}" for="radius" />
                            <h:inputText id="radius" value="#{mapPointController.selected.radius}" />
                            <h:outputLabel value="#{text.Label}" for="label" />
                            <h:inputText id="label" value="#{mapPointController.selected.label}" required="true" requiredMessage="#{text.Required}"/>
                            <h:outputLabel value="#{text.ShortInfo}" for="shortInfo" />
                            <h:inputText id="shortInfo" value="#{mapPointController.selected.shortInfo}" />
                            <h:outputLabel value="#{text.FullInfo}" for="fullInfo" />
                            <h:inputTextarea rows="4" cols="30" id="fullInfo" value="#{mapPointController.selected.fullInfo}" />
                            <h:outputLabel value="#{text.Region}" for="Region" />
                            <h:selectOneMenu id="region" value="#{mapPointController.selected.region}">                                
                                <f:selectItems value="#{applicationUtil.getListValue(mapPointController.selected.region)}" var="c" itemLabel="#{c.label}" itemValue="#{c.value}" />
                            </h:selectOneMenu>
                        </h:panelGrid>
                        <div class="marginLeft">
                            <h:commandLink action="#{mapPointController.update}" value="#{text.Save}"/>
                            <br />
                            <h:commandLink action="#{mapPointController.prepareList}" value="#{text.Back}" immediate="true"/>
                        </div>
                    </h:form>
                </div>
            </div>
        </ui:define>
    </ui:composition>
</html>

PanelAdministracyjny/web/mapPoint/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">
    <ui:composition template="/WEB-INF/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{text.ListMapPointTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:form styleClass="jsfcrud_list_form">
                <h:outputText escape="false" value="#{text.DataEmpty}" rendered="#{mapPointController.items.rowCount == 0}"/>                               
                <div id="table">
                    <div id="table2">
                        <ui:repeat value="#{mapPointController.items}" var="item">
                            <table style="margin-bottom: 10px; width: 100%;">
                                <tr>
                                    <th title="#{applicationUtil.tabTooltip(text.Label)}" colspan="2"><h:commandLink action="#{mapPointController.prepareView()}" value="#{item.label}" /></th>                           
                                    <td title="#{applicationUtil.tabTooltip(text.LastUpdate)}" colspan="2" style="white-space: nowrap;">#{applicationUtil.convertDate(item.lastUpdate)}</td>
                                </tr>
                                <tr>
                                    <td title="#{applicationUtil.tabTooltip(text.ShortInfo)}" colspan="2">#{item.shortInfo == "" ? '-' : item.shortInfo}</td>
                                    <td title="#{applicationUtil.tabTooltip(text.Latitude)}" colspan="2">#{applicationUtil.roundDouble(item.latitude)}</td>                      
                                </tr>     
                                <tr>
                                    <td title="#{applicationUtil.tabTooltip(text.Address)}">#{item.address == "" ? '-' : item.address}</td>
                                    <td title="#{applicationUtil.tabTooltip(text.Region)}">#{item.region == "" ? '-' : item.region}</td>
                                    <td title="#{applicationUtil.tabTooltip(text.Longitude)}" colspan="2">#{applicationUtil.roundDouble(item.longitude)}</td>                      
                                </tr>  
                                <tr>
                                    <td title="#{applicationUtil.tabTooltip(text.FullInfo)}" colspan="2" rowspan="4">#{item.fullInfo == "" ? '-' : item.fullInfo}</td>
                                    <td title="#{applicationUtil.tabTooltip(text.Radius)}" colspan="2">#{item.radius == null ? '-' : item.radius}</td>
                                </tr>
                                <tr>
                                    <td style="width: 60px;"><h:commandLink action="#{mapPointController.prepareEdit()}" value="#{text.Edit}" rendered="#{loginHelper.admin}"/></td>
                                    <td style="width: 60px;"><h:commandLink action="#{mapPointController.destroy()}" value="#{text.Delete}" rendered="#{loginHelper.admin}"/></td>
                                </tr>
                                <tr>
                                    <td colspan="2"/>
                                </tr>
                            </table>
                        </ui:repeat>
                        <h:panelGroup rendered="#{mapPointController.items.rowCount > 0}">
                            <h:outputText value="#{mapPointController.pagination.pageFirstItem + 1}..#{mapPointController.pagination.pageLastItem + 1}/#{mapPointController.pagination.itemsCount}"/>&nbsp;
                            <h:commandLink action="#{mapPointController.previous}" value="#{text.Previous} #{mapPointController.pagination.pageSize}" rendered="#{mapPointController.pagination.hasPreviousPage}"/>&nbsp;
                            <h:commandLink action="#{mapPointController.next}" value="#{text.Next} #{mapPointController.pagination.pageSize}" rendered="#{mapPointController.pagination.hasNextPage}"/>&nbsp;
                        </h:panelGroup>
                    </div>                    
                </div>                
            </h:form>
        </ui:define>
    </ui:composition>
</html>

PanelAdministracyjny/web/mapPoint/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">
    <ui:composition template="/WEB-INF/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{text.ViewMapPointTitle}"></h:outputText>
        </ui:define>        
        <ui:define name="body">
            <div id="table">
                <div id="table2">
                    <h:form id="viewForm" prependId="false">
                        <h:panelGrid columns="2">
                            <h:outputText value="#{text.Id}"/>
                            <h:outputText value="#{mapPointController.selected.id}"/>
                            <h:outputText value="#{text.Latitude}"/>
                            <h:outputText value="#{mapPointController.selected.latitude}" id="otLat"/>
                            <h:outputText value="#{text.Longitude}"/>
                            <h:outputText value="#{mapPointController.selected.longitude}" id="otLon"/>
                            <h:outputText value="#{text.Radius}"/>
                            <h:outputText value="#{mapPointController.selected.radius}"/>
                            <h:outputText value="#{text.Label}"/>
                            <h:outputText value="#{mapPointController.selected.label}"/>
                            <h:outputText value="#{text.ShortInfo}"/>
                            <h:outputText value="#{mapPointController.selected.shortInfo}"/>
                            <h:outputText value="#{text.FullInfo}"/>
                            <h:outputText value="#{mapPointController.selected.fullInfo}"/>
                            <h:outputText value="#{text.LastUpdate}"/>
                            <h:outputText value="#{mapPointController.selected.lastUpdate}"/>                    
                            <h:outputText value="#{text.Region}"/>
                            <h:outputText value="#{mapPointController.selected.region}" />
                            <h:outputText value="#{text.Address}"/>
                            <h:outputText value="#{mapPointController.selected.address}" />
                        </h:panelGrid>
                        <div class="marginLeft">
                            <h:commandLink action="#{mapPointController.prepareList()}" value="#{text.Back}"/>
                            <br />
                            <h:commandLink action="#{mapPointController.destroyAndView()}" value="#{text.Delete}" rendered="#{loginHelper.admin}"/>
                            <br />
                            <h:commandLink action="#{mapPointController.prepareEdit()}" value="#{text.Edit}" rendered="#{loginHelper.admin}"/>
                        </div>
                    </h:form>
                </div>
            </div>
        </ui:define>
    </ui:composition>    
</html>